Traceback (most recent call last):
  File "traceback.py", line 4, in <module>
    raise Exception("This is an error message")
Exception: This is an error message
